"""MATLAB-parity tests for tenor_saxs.protocol.tenor_protocol.

Runs the full Python pipeline against the real MATLAB reference output
(``matlab/run_reference_export.m``'s 144-case deterministic grid,
generated by running the vendored MATLAB code under Octave -- see
the internal validation notes' "Validated to date" section for the numbers this test
formalizes).

Reference data lives outside the git repo (sibling ``tenor-saxs-v2-data``
directory) and is gitignored, so every test here skips gracefully if the
file is missing rather than failing.
"""

from __future__ import annotations

import pickle
import time
from pathlib import Path

import numpy as np
import pytest

from tenor_saxs import protocol

_REFERENCE_DIR = Path(__file__).parent.parent.parent / "tenor-saxs-v2-data" / "octave-reference"
_DETERMINISTIC_GRID_PATH = _REFERENCE_DIR / "deterministic_grid.pkl"
_NOISY_GRID_PATH = _REFERENCE_DIR / "noisy_grid.mat"

_SKIP_DETERMINISTIC = pytest.mark.skipif(
    not _DETERMINISTIC_GRID_PATH.exists(),
    reason=f"MATLAB reference file not found at {_DETERMINISTIC_GRID_PATH} (gitignored, generated separately)",
)
_SKIP_NOISY = pytest.mark.skipif(
    not _NOISY_GRID_PATH.exists(),
    reason=f"MATLAB reference file not found at {_NOISY_GRID_PATH} (gitignored, generated separately)",
)


@pytest.fixture(scope="module")
def deterministic_ok_rows():
    with open(_DETERMINISTIC_GRID_PATH, "rb") as f:
        data = pickle.load(f)
    ok_rows = [row for row in data if row["status"] == "ok"]
    assert len(ok_rows) > 0, "expected at least one status=='ok' row in the deterministic grid"
    return ok_rows


@_SKIP_DETERMINISTIC
def test_deterministic_grid_matlab_parity(deterministic_ok_rows):
    """Run protocol.tenor_protocol on every MATLAB-successful case and check:
    (a) it never raises, (b) median |Rg error| < 1e-4, (c) median |BestV
    error| < 1e-2 (over rows where both sides are finite), (d) median
    |Yg100 error| < 1e-2. Ym210 is recorded but only sanity-checked with a
    very loose bound -- see module docstring / the internal validation notes for the
    known ill-conditioning outlier (near-zero m1 coefficient blowing up the
    Ym210 ratio for one high-V Gaussian-chain case; not a bug).
    """
    rows = deterministic_ok_rows

    rg_errors = []
    bestv_errors = []
    yg100_errors = []
    ym210_errors = []
    failures = []

    t0 = time.time()
    for row in rows:
        try:
            result = protocol.tenor_protocol(
                row["I"],
                row["qx"],
                row["qy"],
                row["Phi2"],
                weight_mode="intensity",
                use_r3=False,
                use_g3=False,
            )
        except Exception as exc:  # noqa: BLE001 - we want to collect ALL failures
            failures.append((row["CaseID"], repr(exc)))
            continue

        rg_errors.append(abs(result.rg - row["Rg"]))
        yg100_errors.append(abs(result.observed["Yg100"] - row["Yg100"]))
        ym210_errors.append(abs(result.observed["Ym210"] - row["Ym210"]))
        if np.isfinite(result.best_v) and np.isfinite(row["BestV"]):
            bestv_errors.append(abs(result.best_v - row["BestV"]))
    elapsed = time.time() - t0

    if failures:
        detail = "\n".join(f"  CaseID={cid}: {err}" for cid, err in failures[:5])
        pytest.fail(
            f"tenor_protocol raised on {len(failures)}/{len(rows)} MATLAB-successful rows "
            f"(expected 0). First few failures:\n{detail}"
        )

    n_per_call = elapsed / len(rows)
    # A recent perf fix brought this to ~0.1s/call; flag (not fail) a
    # dramatic regression via a generous ceiling so it's still visible in
    # test output without being a flaky hard failure on slower machines.
    print(
        f"\ntenor_protocol MATLAB-parity run: {len(rows)} rows in {elapsed:.2f}s "
        f"({n_per_call * 1000:.1f} ms/call)"
    )
    if n_per_call > 2.0:
        pytest.fail(
            f"tenor_protocol took {n_per_call * 1000:.1f} ms/call on average, "
            "far above the ~100 ms/call expected after the perf fix -- possible regression."
        )

    median_rg_error = float(np.median(rg_errors))
    median_bestv_error = float(np.median(bestv_errors)) if bestv_errors else float("nan")
    median_yg100_error = float(np.median(yg100_errors))
    median_ym210_error = float(np.median(ym210_errors))
    max_ym210_error = float(np.max(ym210_errors))

    print(f"median |Rg error|    = {median_rg_error:.3e} (n={len(rg_errors)})")
    print(f"median |BestV error| = {median_bestv_error:.3e} (n={len(bestv_errors)})")
    print(f"median |Yg100 error| = {median_yg100_error:.3e} (n={len(yg100_errors)})")
    print(f"median |Ym210 error| = {median_ym210_error:.3e}, max = {max_ym210_error:.3e} (not asserted tightly)")

    assert median_rg_error < 1e-4
    assert len(bestv_errors) > 0, "no rows had finite BestV on both sides"
    assert median_bestv_error < 1e-2
    assert median_yg100_error < 1e-2
    # Loose sanity check only: the known Ym210 outlier (ill-conditioned
    # near-zero m1 coefficient) can be large; just guard against something
    # catastrophically worse than the documented max (~13.3).
    assert max_ym210_error < 20.0


@_SKIP_NOISY
def test_noisy_grid_statistical_sanity():
    """Coarse statistical sanity check against the noisy-replicate sweep.

    The .mat file stores MATLAB's own per-replicate BestV/Rg summary
    statistics (grouped by noise level / peak-photon count) plus the single
    noiseless base image (I0, qx, qy) and the true (V, phi2) used to
    generate it -- but not the individual MATLAB noisy images themselves
    (MATLAB's RNG draws are not saved). So this test reconstructs its own
    noisy replicates from I0 (same shot-noise model as
    simulation.scatter2d), runs them through Python's own tenor_protocol,
    and checks only coarse, RNG-independent statistical properties:

    1. At the highest photon counts (least noise), Python's median BestV
       should be within a generous tolerance of both the true V and
       MATLAB's own median BestV at that noise level.
    2. The spread of BestV across replicates should shrink as photon count
       increases, in both MATLAB's data and Python's reconstruction.

    This is NOT a bit-exact comparison -- MATLAB and NumPy RNG streams
    differ, so per-replicate values are expected to differ.
    """
    import scipy.io as sio

    data = sio.loadmat(str(_NOISY_GRID_PATH), simplify_cells=True)
    qx = np.asarray(data["qx"], dtype=float)
    qy = np.asarray(data["qy"], dtype=float)
    i0 = np.asarray(data["I0"], dtype=float)
    phi2 = float(data["noise_phi2"])
    true_v = float(data["noise_V"])
    peak_photons = np.atleast_1d(data["peakPhotons"]).astype(float)
    matlab_results = data["noisyResults"]

    # Group MATLAB's own results by noise level (1-based NoiseLevelIndex).
    matlab_by_level: dict[int, list[float]] = {}
    for entry in matlab_results:
        if entry.get("status") != "ok":
            continue
        best_v = float(entry["BestV"])
        if not np.isfinite(best_v):
            # MATLAB's own "ok" status does not guarantee a finite BestV
            # (e.g. combine_estimates can legitimately return NaN if no
            # observable was usable for a given noisy replicate).
            continue
        level = int(entry["NoiseLevelIndex"])
        matlab_by_level.setdefault(level, []).append(best_v)

    n_replicates = 8  # smaller than MATLAB's 20, this is only a coarse check
    rng = np.random.default_rng(12345)

    python_by_level: dict[int, list[float]] = {}
    for level_idx, peak in enumerate(peak_photons, start=1):
        estimates = []
        for _ in range(n_replicates):
            noisy = i0 * peak
            noisy = noisy + np.sqrt(np.clip(noisy, 0.0, None)) * rng.standard_normal(noisy.shape)
            noisy = noisy / peak
            noisy[noisy < 0] = 0.0
            try:
                result = protocol.tenor_protocol(
                    noisy, qx, qy, phi2, weight_mode="intensity", use_r3=False, use_g3=False
                )
            except Exception:
                continue
            if np.isfinite(result.best_v):
                estimates.append(result.best_v)
        python_by_level[level_idx] = estimates

    # --- 1. Highest-photon-count (least noisy) level should be reasonably close to truth.
    highest_level = len(peak_photons)
    assert matlab_by_level.get(highest_level), "no usable MATLAB replicates at the highest photon level"
    assert python_by_level.get(highest_level), "no usable Python replicates at the highest photon level"

    matlab_median_high = float(np.median(matlab_by_level[highest_level]))
    python_median_high = float(np.median(python_by_level[highest_level]))

    print(f"\nhighest photon level ({peak_photons[-1]:.0f} peak photons):")
    print(f"  true V = {true_v}")
    print(f"  MATLAB median BestV = {matlab_median_high:.4f} (n={len(matlab_by_level[highest_level])})")
    print(f"  Python median BestV = {python_median_high:.4f} (n={len(python_by_level[highest_level])})")

    assert abs(python_median_high - true_v) < 0.1
    assert abs(python_median_high - matlab_median_high) < 0.1

    # --- 2. Spread should shrink from lowest to highest photon count, in both datasets.
    lowest_level = 1
    if matlab_by_level.get(lowest_level) and python_by_level.get(lowest_level):
        matlab_spread_low = float(np.std(matlab_by_level[lowest_level]))
        matlab_spread_high = float(np.std(matlab_by_level[highest_level]))
        python_spread_low = float(np.std(python_by_level[lowest_level]))
        python_spread_high = float(np.std(python_by_level[highest_level]))

        print(f"  MATLAB BestV std: low-photon={matlab_spread_low:.4f}, high-photon={matlab_spread_high:.4f}")
        print(f"  Python BestV std: low-photon={python_spread_low:.4f}, high-photon={python_spread_high:.4f}")

        assert matlab_spread_high < matlab_spread_low
        assert python_spread_high < python_spread_low
